# Generated by Django 2.1.7 on 2019-03-26 15:22

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogries',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='catogry',
            new_name='category',
        ),
    ]
