# Generated by Django 2.1.7 on 2019-03-26 15:28

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('api', '0002_auto_20190326_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
