# Generated by Django 2.1.7 on 2019-03-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cart_throughcartitemmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throughcartitemmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='through', to='api.Item'),
        ),
    ]
